/* eslint-disable react-hooks/set-state-in-effect, react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
export interface AuthUser { id: string; name: string; email: string; }
interface AuthContextValue { currentUser: AuthUser | null; token: string | null; isAuthenticated: boolean; isLoading: boolean; login: (email: string, password: string) => Promise<void>; register: (name: string, email: string, password: string, confirmPassword: string) => Promise<void>; logout: () => void; }
const AuthContext = createContext<AuthContextValue | undefined>(undefined);
const request = async (path: string, body: object) => { const response = await fetch(`${API_URL}/api/auth/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Authentication request failed'); return data as { token: string; user: AuthUser }; };
export function AuthProvider({ children }: { children: ReactNode }) { const [token, setToken] = useState<string | null>(() => localStorage.getItem('auth_token')); const [currentUser, setCurrentUser] = useState<AuthUser | null>(() => { const saved = localStorage.getItem('auth_user'); return saved ? JSON.parse(saved) as AuthUser : null; }); const [isLoading, setIsLoading] = useState(true); const persist = (data: { token: string; user: AuthUser }) => { localStorage.setItem('auth_token', data.token); localStorage.setItem('auth_user', JSON.stringify(data.user)); setToken(data.token); setCurrentUser(data.user); };
  const logout = () => { localStorage.removeItem('auth_token'); localStorage.removeItem('auth_user'); setToken(null); setCurrentUser(null); };
  useEffect(() => { if (!token) { setIsLoading(false); return; } fetch(`${API_URL}/api/auth/me`, { headers: { Authorization: `Bearer ${token}` } }).then(async response => { if (!response.ok) throw new Error(); const data = await response.json() as { user: AuthUser }; setCurrentUser(data.user); localStorage.setItem('auth_user', JSON.stringify(data.user)); }).catch(logout).finally(() => setIsLoading(false)); }, [token]);
  const value = useMemo(() => ({ currentUser, token, isAuthenticated: Boolean(token && currentUser), isLoading, login: async (email: string, password: string) => persist(await request('login', { email, password })), register: async (name: string, email: string, password: string, confirmPassword: string) => persist(await request('register', { name, email, password, confirmPassword })), logout }), [token, currentUser, isLoading]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
export const useAuth = () => { const context = useContext(AuthContext); if (!context) throw new Error('useAuth must be used within AuthProvider'); return context; };
